version: '3'

services:
  web:
    container_name: felix
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongol
    image: mongo
    ports:
      - "27017:27017"
